# Numpy

Introduction to Numpy Array
Welcome to this lesson on understanding Numpy arrays! Today, we will be focusing on numerical computations with Numpy, specifically around the creation, manipulation, and operations of Numpy arrays.

Numpy, short for Numerical Python, is an essential library for performing numerical computations in Python. It has support for arrays (like lists in Python, but can store items of the same type), multidimensional arrays, matrices, and a large collection of high-level mathematical functions.

In the world of data manipulation using Python, understanding and being able to use Numpy arrays allows us to efficiently manage numerical data.

***Creating a Numpy Array***
The most common way to create a Numpy array is by using the numpy.array() function. You can pass any sequence-like object into this function, and it will be converted into an array. Let's convert a regular Python list into a Numpy array:

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Executing these lines creates a one-dimensional Numpy array np_array with the same elements as our regular Python list py_list.

We can also create two-dimensional arrays (similar to matrices). Let's convert a list of lists into a 2D Numpy array:

In [4]:
array2D = np.array([[1,2],[3,4]])
print(array2D)

[[1 2]
 [3 4]]


### Attributes of Numpy Arrays
Numpy arrays come equipped with several attributes for gaining more insights:

ndim tells us the number of dimensions of the array.
shape gives us the size of each dimension.
size tells us the total number of elements in the array.
dtype tells us the data type of the elements in the array.
Let's create a 2D array and use these attributes:

In [12]:
my_array = np.array([[12,13,14],[31,41,34],[9,0,7]])

print("Dimension of array",my_array.ndim)
print("Shape of array",my_array.shape)
print("Data Type of element",my_array.dtype)
print("Size: ", my_array.size)  

Dimension of array 2
Shape of array (3, 3)
Data Type of element int32
Size:  9


### Array Manipulations: Indexing, Slicing and Reshaping Numpy Arrays
Numpy arrays can be manipulated in various ways. For instance, we can access specific positions (indexing) and even slices of the array (slicing), or change the shape of the array (reshaping).

Let's play around with these manipulations:

In [27]:
#my_array = np.array([[12,13,14],[31,41,34],[9,0,7]])

print("First sublist of ARRAY",my_array[0])
print("Second element of first sublist of ARRAY",my_array[0][1])
# Indexing: access the element at the second row, third column
print("Indexed Value: ", my_array[1, 2]) # Indexed Value:  3

# Slicing: access the second row 
print("second row", my_array[1:2])

# silice 3 row first 2 element
print(my_array[2][0:2])


# Reshape the array to 2 rows and 3 columns (only applicable if the reshaped total size equals the original size)
new_array = np.array([[2,3],[4,5],[7,6]])
reshaped_array = new_array.reshape(2,3)
print("Reshaped array \n",reshaped_array)



First sublist of ARRAY [12 13 14]
Second element of first sublist of ARRAY 13
Indexed Value:  34
second row [[31 41 34]]
[9 0]
Reshaped array 
 [[2 3 4]
 [5 7 6]]


In the code snippet shown above, indexing is used to access a specific element in the array, slicing is used to access a range of elements, and reshaping is used to reconfigure the layout of the array while keeping the data intact.

### Array Operations
We can perform arithmetic operations such as addition, subtraction, multiplication, and division on Numpy arrays, which calculates the outcome element-wise.

In [35]:
np_array1 = np.array([1,2,3])
np_array2 = np.array([4,5,6])

# Addition 
print("addition of Two arrays :", np_array1 + np_array2)

# Subtraction
print("subtraction of Two arrays :",np_array1 - np_array2)

# Multiplication
print("Multiplication of Two arrays :", np_array1 * np_array2) # Output: [4 10 18]

# Division
print("Division of Two arrays :",np_array1 / np_array2) # Output: [0.25 0.4 0.5]

addition of Two arrays : [5 7 9]
subtraction of Two arrays : [-3 -3 -3]
Multiplication of Two arrays : [ 4 10 18]
Division of Two arrays : [0.25 0.4  0.5 ]


Here, every operation is applied to each corresponding pair of elements in np_array1 and np_array2, resulting in a new array consisting of these outcomes.